export const exerciseSlugs = [
  "labirinto",
  "caca-palavras",
  "torre-de-hanoi",
  "resta-um",
  "sequencia-inteligente",
  "reflexo-fantasmas",
  "torre-de-londres",
  "quebra-cabeca-emoji",
  "afirmou-bateu",
  "memoria-mix",
  "desafio-das-cores",
  "emoji-alvo",
  "intruso-das-palavras",
  "clique-no-momento-certo",
  "caca-circulos",
  "sequencia-numerica",
  "busca-do-simbolo",
  "ordem-das-acoes",
  "palavra-emoji",
] as const;

export type ExerciseSlug = (typeof exerciseSlugs)[number];

export type ExerciseDefinition = {
  number: string;
  slug: ExerciseSlug;
  title: string;
  category: string;
  description: string;
  objective: string;
  image: string;
  imageAlt: string;
  skills: string[];
  instructions: string[];
  estimatedTime: string;
  level: string;
  related: ExerciseSlug[];
};

export const exerciseCatalog = [
  {
    number: "01",
    slug: "labirinto",
    title: "Labirinto",
    category: "Planejamento",
    description: "Planeje caminhos, antecipe movimentos e acompanhe sua orientação visual.",
    objective: "Chegar ao destino por uma rota eficiente, comparando alternativas antes de cada movimento.",
    image: "/exercises/labirinto.webp",
    imageAlt: "Ilustração de um percurso em labirinto com ponto de partida e chegada",
    skills: ["Planejamento", "Orientação visuoespacial", "Antecipação", "Monitoramento de rota"],
    instructions: ["Observe o labirinto antes de mover.", "Use o teclado ou os botões direcionais para chegar ao destino.", "Repita o nível tentando reduzir a quantidade de movimentos."],
    estimatedTime: "3–6 min",
    level: "3 níveis",
    related: ["torre-de-londres", "torre-de-hanoi", "resta-um"],
  },
  {
    number: "02",
    slug: "caca-palavras",
    title: "Caça-Palavras",
    category: "Linguagem",
    description: "Localize palavras enquanto exercita atenção visual e reconhecimento verbal.",
    objective: "Encontrar palavras em diferentes direções por meio de varredura visual organizada.",
    image: "/exercises/caca-palavras.webp",
    imageAlt: "Grade de letras com palavras destacadas em diferentes direções",
    skills: ["Atenção visual", "Reconhecimento verbal", "Varredura sistemática", "Persistência"],
    instructions: ["Leia a lista de palavras-alvo.", "Selecione a primeira e a última letra de cada palavra.", "Procure na horizontal, vertical e diagonal até completar a lista."],
    estimatedTime: "4–8 min",
    level: "Progressivo",
    related: ["intruso-das-palavras", "busca-do-simbolo", "emoji-alvo"],
  },
  {
    number: "03",
    slug: "torre-de-hanoi",
    title: "Torre de Hanói",
    category: "Raciocínio",
    description: "Organize movimentos com estratégia e respeite as regras do desafio.",
    objective: "Transferir toda a torre para a última estaca com poucos movimentos e sem colocar discos maiores sobre menores.",
    image: "/exercises/torre-de-hanoi.webp",
    imageAlt: "Três estacas e discos coloridos de diferentes tamanhos da Torre de Hanói",
    skills: ["Raciocínio lógico", "Memória de trabalho", "Planejamento", "Controle de impulsos"],
    instructions: ["Selecione a estaca de origem e depois a de destino.", "Mova somente o disco do topo e respeite a ordem de tamanhos.", "Leve todos os discos à terceira estaca e compare seus movimentos com o mínimo."],
    estimatedTime: "4–10 min",
    level: "3 a 5 discos",
    related: ["torre-de-londres", "labirinto", "resta-um"],
  },
  {
    number: "04",
    slug: "resta-um",
    title: "Resta Um",
    category: "Raciocínio visual",
    description: "Avalie possibilidades e encontre uma sequência eficiente de jogadas.",
    objective: "Remover peças por saltos válidos até deixar somente uma no tabuleiro.",
    image: "/exercises/resta-um.webp",
    imageAlt: "Tabuleiro em cruz do exercício Resta Um com peças circulares",
    skills: ["Resolução de problemas", "Antecipação", "Raciocínio visuoespacial", "Flexibilidade"],
    instructions: ["Selecione uma peça que tenha outra ao lado e um espaço vazio adiante.", "Salte na horizontal ou vertical; a peça ultrapassada será removida.", "Use desfazer para revisar decisões e tente terminar com uma única peça."],
    estimatedTime: "5–12 min",
    level: "Desafio único",
    related: ["torre-de-hanoi", "sequencia-inteligente", "labirinto"],
  },
  {
    number: "05",
    slug: "sequencia-inteligente",
    title: "Sequência Inteligente",
    category: "Lógica",
    description: "Observe o padrão e escolha o elemento que dá continuidade à sequência.",
    objective: "Inferir regras numéricas e padrões alternados, justificando mentalmente cada resposta.",
    image: "/exercises/sequencia-inteligente.webp",
    imageAlt: "Cartões numéricos organizados como uma sequência lógica",
    skills: ["Raciocínio indutivo", "Identificação de padrões", "Flexibilidade cognitiva", "Atenção"],
    instructions: ["Compare as diferenças entre termos consecutivos.", "Escolha uma das alternativas para completar o padrão.", "Leia a explicação e avance para uma nova sequência."],
    estimatedTime: "3–7 min",
    level: "3 níveis",
    related: ["sequencia-numerica", "resta-um", "desafio-das-cores"],
  },
  {
    number: "06",
    slug: "reflexo-fantasmas",
    title: "Reflexo Fantasmas",
    category: "Atenção",
    description: "Responda a estímulos visuais com foco, rapidez e precisão.",
    objective: "Responder somente ao alvo correto e inibir respostas diante de distratores.",
    image: "/exercises/reflexo-fantasmas.webp",
    imageAlt: "Fantasma claro em destaque entre personagens coloridos",
    skills: ["Atenção sustentada", "Controle inibitório", "Discriminação visual", "Tempo de resposta"],
    instructions: ["Escolha um nível e inicie a rodada.", "Clique apenas quando aparecer o fantasma branco.", "Evite antecipações e acompanhe acertos e falsos alarmes."],
    estimatedTime: "2–5 min",
    level: "3 níveis",
    related: ["clique-no-momento-certo", "afirmou-bateu", "emoji-alvo"],
  },
  {
    number: "07",
    slug: "torre-de-londres",
    title: "Torre de Londres",
    category: "Funções executivas",
    description: "Antecipe etapas e organize movimentos para alcançar o objetivo proposto.",
    objective: "Reproduzir um modelo-alvo respeitando a capacidade das hastes e buscando a rota mais curta.",
    image: "/exercises/torre-de-londres.webp",
    imageAlt: "Bolas coloridas distribuídas em três hastes da Torre de Londres",
    skills: ["Planejamento", "Memória de trabalho", "Monitoramento", "Resolução de problemas"],
    instructions: ["Compare a configuração atual com o modelo-alvo.", "Selecione a haste de origem e a de destino para mover a bola do topo.", "Respeite as capacidades e tente alcançar o alvo com a referência mínima de movimentos."],
    estimatedTime: "4–9 min",
    level: "3 níveis",
    related: ["torre-de-hanoi", "ordem-das-acoes", "labirinto"],
  },
  {
    number: "08",
    slug: "quebra-cabeca-emoji",
    title: "Quebra-Cabeça Emoji",
    category: "Percepção visual",
    description: "Reconstrua a ordem observando posições, detalhes e relações entre as peças.",
    objective: "Organizar um tabuleiro deslizante numerado usando o espaço vazio para planejar cada troca.",
    image: "/exercises/quebra-cabeca-emoji.webp",
    imageAlt: "Quebra-cabeça deslizante formado por peças com emojis",
    skills: ["Percepção visuoespacial", "Planejamento", "Memória de posição", "Persistência"],
    instructions: ["Observe a posição esperada de cada peça numerada.", "Mova apenas uma peça vizinha ao espaço vazio.", "Continue até ordenar todo o quadro e tente diminuir erros e movimentos."],
    estimatedTime: "4–10 min",
    level: "Grade 3 × 3",
    related: ["labirinto", "resta-um", "torre-de-londres"],
  },
  {
    number: "09",
    slug: "afirmou-bateu",
    title: "Afirmou, Bateu!",
    category: "Controle inibitório",
    description: "Escolha a resposta adequada e pratique o controle de respostas automáticas.",
    objective: "Decidir se palavra e direção visual combinam, resistindo à interferência entre informações concorrentes.",
    image: "/exercises/afirmou-bateu.webp",
    imageAlt: "Setas e palavras direcionais em uma atividade de controle inibitório",
    skills: ["Controle inibitório", "Atenção seletiva", "Velocidade de decisão", "Monitoramento de erros"],
    instructions: ["Observe simultaneamente a palavra e a seta.", "Responda se as duas informações combinam.", "Priorize precisão e só então tente responder mais rapidamente."],
    estimatedTime: "2–5 min",
    level: "3 ritmos",
    related: ["desafio-das-cores", "reflexo-fantasmas", "clique-no-momento-certo"],
  },
  {
    number: "10",
    slug: "memoria-mix",
    title: "Memória Mix",
    category: "Memória",
    description: "Encontre associações e mantenha informações ativas ao longo da atividade.",
    objective: "Localizar pares ao recordar a identidade e a posição de cartas vistas anteriormente.",
    image: "/exercises/memoria-mix.webp",
    imageAlt: "Cartas ilustradas viradas em uma atividade de memória visual",
    skills: ["Memória visual", "Memória de trabalho", "Atenção", "Estratégia de busca"],
    instructions: ["Vire duas cartas por vez.", "Memorize símbolo e posição quando não formarem um par.", "Encontre todos os pares usando o menor número de tentativas possível."],
    estimatedTime: "3–7 min",
    level: "3 níveis",
    related: ["sequencia-numerica", "busca-do-simbolo", "caca-palavras"],
  },
  {
    number: "11",
    slug: "desafio-das-cores",
    title: "Desafio das Cores",
    category: "Flexibilidade cognitiva",
    description: "Alterne critérios e mantenha o foco diante de informações concorrentes.",
    objective: "Nomear a cor visual e ignorar o significado automático da palavra escrita.",
    image: "/exercises/desafio-das-cores.webp",
    imageAlt: "Nomes de cores escritos em tonalidades diferentes do significado",
    skills: ["Flexibilidade cognitiva", "Controle inibitório", "Atenção seletiva", "Velocidade de processamento"],
    instructions: ["Ignore o que a palavra diz.", "Selecione a cor da tinta usada para exibi-la.", "Avance pelas rodadas preservando precisão sob limite de tempo."],
    estimatedTime: "2–5 min",
    level: "3 níveis",
    related: ["afirmou-bateu", "reflexo-fantasmas", "sequencia-inteligente"],
  },
  {
    number: "12",
    slug: "emoji-alvo",
    title: "Emoji Alvo",
    category: "Atenção seletiva",
    description: "Procure o alvo entre estímulos semelhantes e exercite a varredura visual.",
    objective: "Encontrar rapidamente a única figura idêntica ao modelo entre distratores parecidos.",
    image: "/exercises/emoji-alvo.webp",
    imageAlt: "Emoji-alvo destacado diante de uma grade de expressões semelhantes",
    skills: ["Atenção seletiva", "Discriminação visual", "Varredura", "Velocidade de processamento"],
    instructions: ["Memorize os detalhes do emoji-modelo.", "Examine o quadro de maneira organizada.", "Selecione a correspondência exata e avance pelas rodadas."],
    estimatedTime: "2–5 min",
    level: "3 níveis",
    related: ["busca-do-simbolo", "caca-circulos", "caca-palavras"],
  },
  {
    number: "13",
    slug: "intruso-das-palavras",
    title: "Intruso das Palavras",
    category: "Linguagem",
    description: "Compare significados e identifique qual palavra não pertence ao grupo.",
    objective: "Reconhecer categorias semânticas e excluir o elemento que não compartilha a relação principal.",
    image: "/exercises/intruso-das-palavras.webp",
    imageAlt: "Grupo de palavras com uma opção diferente das demais",
    skills: ["Semântica", "Categorização", "Raciocínio verbal", "Flexibilidade"],
    instructions: ["Leia todas as palavras antes de responder.", "Identifique a categoria compartilhada pela maioria.", "Escolha a palavra intrusa e use o feedback para revisar a relação."],
    estimatedTime: "3–6 min",
    level: "Progressivo",
    related: ["palavra-emoji", "caca-palavras", "sequencia-inteligente"],
  },
  {
    number: "14",
    slug: "clique-no-momento-certo",
    title: "Clique no Momento Certo",
    category: "Tempo de resposta",
    description: "Aguarde o sinal correto para responder com atenção e precisão.",
    objective: "Sustentar a prontidão e responder ao sinal visual sem antecipar o clique.",
    image: "/exercises/clique-no-momento-certo.webp",
    imageAlt: "Botão luminoso representando o momento certo para responder",
    skills: ["Atenção sustentada", "Tempo de reação", "Controle inibitório", "Prontidão"],
    instructions: ["Inicie e aguarde enquanto o quadro estiver em espera.", "Clique somente quando o sinal ficar verde.", "Repita as tentativas e compare consistência, não apenas velocidade."],
    estimatedTime: "2–4 min",
    level: "5 tentativas",
    related: ["reflexo-fantasmas", "afirmou-bateu", "caca-circulos"],
  },
  {
    number: "15",
    slug: "caca-circulos",
    title: "Caça-Círculos",
    category: "Atenção visual",
    description: "Localize estímulos específicos em uma atividade de busca visual.",
    objective: "Encontrar todos os círculos preenchidos entre formas semelhantes antes do fim do tempo.",
    image: "/exercises/caca-circulos.webp",
    imageAlt: "Grade de formas geométricas contendo círculos-alvo",
    skills: ["Atenção visual", "Varredura sistemática", "Discriminação", "Velocidade"],
    instructions: ["Escolha o nível e observe qual forma deve ser localizada.", "Percorra a grade por linhas ou colunas.", "Selecione todos os círculos preenchidos evitando distratores."],
    estimatedTime: "2–5 min",
    level: "3 níveis",
    related: ["emoji-alvo", "busca-do-simbolo", "caca-palavras"],
  },
  {
    number: "16",
    slug: "sequencia-numerica",
    title: "Sequência Numérica",
    category: "Memória de trabalho",
    description: "Mantenha números na memória e reproduza a sequência apresentada.",
    objective: "Codificar uma série breve de dígitos e recuperá-la na mesma ordem após ela desaparecer.",
    image: "/exercises/sequencia-numerica.webp",
    imageAlt: "Dígitos apresentados em cartões para memorização sequencial",
    skills: ["Memória de trabalho", "Atenção auditiva e visual", "Sequenciamento", "Estratégias de codificação"],
    instructions: ["Observe e memorize os dígitos na ordem apresentada.", "Quando eles desaparecerem, digite ou selecione a sequência completa.", "Avance para séries maiores e use a ajuda somente quando necessário."],
    estimatedTime: "3–7 min",
    level: "Dificuldade adaptativa",
    related: ["memoria-mix", "sequencia-inteligente", "ordem-das-acoes"],
  },
  {
    number: "17",
    slug: "busca-do-simbolo",
    title: "Busca do Símbolo",
    category: "Velocidade de processamento",
    description: "Compare símbolos e encontre correspondências com agilidade e cuidado.",
    objective: "Comparar um símbolo-modelo com alternativas visuais e localizar a cópia exata.",
    image: "/exercises/busca-do-simbolo.webp",
    imageAlt: "Símbolo geométrico sendo comparado com várias alternativas",
    skills: ["Velocidade de processamento", "Atenção seletiva", "Discriminação visual", "Precisão"],
    instructions: ["Observe os traços e a orientação do modelo.", "Compare todas as alternativas antes de escolher.", "Complete as rodadas equilibrando rapidez e precisão."],
    estimatedTime: "2–5 min",
    level: "3 níveis",
    related: ["emoji-alvo", "caca-circulos", "memoria-mix"],
  },
  {
    number: "18",
    slug: "ordem-das-acoes",
    title: "Ordem das Ações",
    category: "Sequenciamento",
    description: "Organize etapas em uma ordem coerente e pratique o planejamento cotidiano.",
    objective: "Reconhecer dependências entre ações e montar uma sequência funcional para situações do dia a dia.",
    image: "/exercises/ordem-das-acoes.webp",
    imageAlt: "Etapas cotidianas organizadas em cartões numerados",
    skills: ["Sequenciamento", "Planejamento cotidiano", "Raciocínio causal", "Revisão"],
    instructions: ["Leia a situação e todas as etapas disponíveis.", "Use os botões para mover cada ação para cima ou para baixo.", "Confira a ordem, revise as posições indicadas e tente novamente."],
    estimatedTime: "4–8 min",
    level: "4 situações",
    related: ["torre-de-londres", "sequencia-numerica", "sequencia-inteligente"],
  },
  {
    number: "19",
    slug: "palavra-emoji",
    title: "Palavra & Emoji",
    category: "Associação",
    description: "Relacione linguagem e informação visual para encontrar a combinação correta.",
    objective: "Associar conceitos verbais a representações visuais usando significado, contexto e inferência.",
    image: "/exercises/palavra-emoji.webp",
    imageAlt: "Palavra ligada a diferentes opções de emojis por associação de significado",
    skills: ["Associação semântica", "Compreensão verbal", "Inferência", "Flexibilidade cognitiva"],
    instructions: ["Leia a palavra e a pista contextual.", "Compare o significado de cada emoji disponível.", "Escolha a melhor associação e use o feedback antes de avançar."],
    estimatedTime: "3–6 min",
    level: "Progressivo",
    related: ["intruso-das-palavras", "caca-palavras", "emoji-alvo"],
  },
] satisfies ExerciseDefinition[];

export function getExercise(slug: string) {
  return exerciseCatalog.find((exercise) => exercise.slug === slug);
}
